name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [8.2, 8.3, 8.4]

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, bcmath, pdo, sqlite
          coverage: none

      - name: Install dependencies (including dev)
        run: composer install --no-interaction --prefer-dist

      - name: Setup SQLite database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Run tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ":memory:"
        run: composer test